### PR TITLE
Update Mijn Blink Afvalkalender

### PR DESCRIPTION
**Pull request by zee-eend**
Add Mijn Blink Afvalkalender

### CODE REVIEW

**Comment by robertraaijmakers** [comment]
Quick question, why didn't you re-use the "newGeneralAfvalkalendersNederland" implementation? As far as I can see this should also work for the Blink afvalkalender.

**Comment by zee-eend** [comment]
Thanks for merging!
I’m no programmer, this is the first thing I ever made, so that’s the reason I didn’t use the general script. I just haven’t seen it haha.

You think it made a difference if I used the general instead of my script?

**Comment by robertraaijmakers** [comment]
It's a good implementation :) Using the available function might have saved you some time ;) But nonetheless as long as it works it works!

The only thing is that when the API / website changes the code changes has to be done on multiple API's instead of one generic function. But I'll leave it for now since it's working and will see if I change it to the generic function later on when other changes need to happen.

**Comment by zee-eend** [comment]
Thanks for the support! ;)

Can’t wait to use it when the app has been updated :)

**Comment by zee-eend** [comment]
When will mijnblink be available in the homey App Store?

**Comment by robertraaijmakers** [comment]
2.5.5 is now available as beta in the store. Hopefully you can test the beta version and after that I will make it publicly available

**Comment by zee-eend** [comment]
I just downloaded Beta, but I don’t see blink in the list when I config the app settings, it’s only in the readme:(

**Comment by robertraaijmakers** [comment]
Sorry, forgot one item that adds the afvalwijzer to the dropdown list in the settings page. Added it and it should be available as beta 2.5.6

**Comment by zee-eend** [comment]
Thank you! It’s right there now :) It’s receiving trash dates, so I think it works. Keep you posted

**Pull request merged**
